const readline = require('readline');
const path = require('path');
const fs = require('fs');

const COLORS = {
  reset: '\x1b[0m', bright: '\x1b[1m', dim: '\x1b[2m',
  cyan: '\x1b[36m', green: '\x1b[32m', yellow: '\x1b[33m',
  red: '\x1b[31m', magenta: '\x1b[35m', gray: '\x1b[90m',
};
const c = (color, text) => `${COLORS[color]}${text}${COLORS.reset}`;

const VALID_TYPES = ['react-app', 'nextjs-app', 'express-api', 'portfolio', 'admin-dashboard', 'landing-page', 'blog', 'docs-site', 'resume-builder', 'tailwind-website'];

function prompt(rl, question) {
  return new Promise(resolve => rl.question(question, resolve));
}

async function create([type, name, ...rest]) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  console.log('');
  console.log(c('magenta', '  ◆ MD Dev Studio — Project Generator'));
  console.log('');

  // Validate or ask for type
  if (!type || !VALID_TYPES.includes(type)) {
    console.log(c('bright', '  Available project types:\n'));
    VALID_TYPES.forEach((t, i) => console.log(`  ${c('cyan', String(i + 1).padStart(2))}. ${t}`));
    console.log('');
    const choice = await prompt(rl, c('yellow', '  Select type (name or number): '));
    const num = parseInt(choice);
    type = isNaN(num) ? choice.trim() : (VALID_TYPES[num - 1] || choice.trim());
    if (!VALID_TYPES.includes(type)) {
      rl.close();
      throw new Error(`Invalid project type: ${type}`);
    }
  }

  // Collect config
  if (!name) name = await prompt(rl, c('yellow', `  Project name [my-${type}]: `)) || `my-${type}`;
  name = name.trim().toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') || `my-${type}`;

  const displayName = await prompt(rl, c('yellow', `  Display name [${toTitle(name)}]: `)) || toTitle(name);
  const description = await prompt(rl, c('yellow', '  Description [A project by MD Dev Studio]: ')) || 'A project by MD Dev Studio';
  const author = await prompt(rl, c('yellow', '  Author [Developer]: ')) || 'Developer';

  let extra = {};
  if (type === 'express-api') {
    const port = await prompt(rl, c('yellow', '  Port [3000]: ')) || '3000';
    extra.port = port.trim();
  }

  const accentColor = await prompt(rl, c('yellow', '  Accent color [#ff79ee]: ')) || '#ff79ee';
  const font = await prompt(rl, c('yellow', '  Font [Inter]: ')) || 'Inter';

  rl.close();

  const config = { name, displayName: displayName.trim(), description: description.trim(), author: author.trim(), accentColor: accentColor.trim(), font: font.trim(), ...extra };

  console.log('');
  console.log(c('cyan', `  ◆ Generating ${type} project "${name}"...`));
  console.log('');

  // Try to use backend API if running, else generate locally
  let result;
  try {
    const res = await fetchWithTimeout(`http://localhost:3001/api/generate/project`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ type, config }),
    });
    if (!res.ok) throw new Error('Backend error');
    result = await res.json();
    if (!result.success) throw new Error(result.error);
    console.log(c('green', `  ✓ Generated ${result.fileCount} files`));
    console.log(c('green', `  ✓ Project saved to: ${result.projectPath}`));
  } catch (err) {
    // Fallback: generate in current directory
    result = generateLocally(type, name, config);
    console.log(c('green', `  ✓ Generated ${result.fileCount} files`));
    console.log(c('green', `  ✓ Project saved to: ${result.projectPath}`));
  }

  console.log('');
  console.log(c('bright', '  Next steps:'));
  console.log('');
  console.log(`  ${c('gray', '$')} cd ${name}`);
  console.log(`  ${c('gray', '$')} npm install`);
  console.log(`  ${c('gray', '$')} npm run dev`);
  console.log('');
  console.log(c('magenta', '  ✨ Happy coding! — MD Dev Studio'));
  console.log('');
}

function generateLocally(type, name, config) {
  const projectPath = path.join(process.cwd(), name);
  fs.mkdirSync(projectPath, { recursive: true });
  fs.mkdirSync(path.join(projectPath, 'src'), { recursive: true });

  // Write basic package.json
  const pkgContent = {
    name, version: '1.0.0', private: true,
    scripts: type === 'express-api' ? { start: 'node src/index.js', dev: 'nodemon src/index.js' } : { dev: 'vite', build: 'vite build', preview: 'vite preview' },
    dependencies: type === 'express-api' ? { express: '^4.18.2', cors: '^2.8.5', dotenv: '^16.3.1' } : { react: '^18.2.0', 'react-dom': '^18.2.0' },
    devDependencies: type === 'express-api' ? { nodemon: '^3.0.2' } : { vite: '^5.0.0', '@vitejs/plugin-react': '^4.2.1', tailwindcss: '^3.4.0' },
  };
  fs.writeFileSync(path.join(projectPath, 'package.json'), JSON.stringify(pkgContent, null, 2));
  fs.writeFileSync(path.join(projectPath, 'README.md'), `# ${config.displayName}\n\n${config.description}\n\nGenerated by MD Dev Studio CLI.\n\n## Quick Start\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n`);
  fs.writeFileSync(path.join(projectPath, '.gitignore'), 'node_modules\ndist\nbuild\n.env\n*.log');
  fs.writeFileSync(path.join(projectPath, 'project.json'), JSON.stringify({ name, type, ...config, created: new Date().toISOString() }, null, 2));

  const files = fs.readdirSync(projectPath, { recursive: true });
  return { projectPath, fileCount: files.length };
}

async function fetchWithTimeout(url, options, timeout = 3000) {
  const controller = new AbortController();
  const id = setTimeout(() => controller.abort(), timeout);
  try {
    const res = await fetch(url, { ...options, signal: controller.signal });
    clearTimeout(id);
    return res;
  } catch (err) {
    clearTimeout(id);
    throw err;
  }
}

function toTitle(str) {
  return str.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

module.exports = create;
