const path = require('path');
const fs = require('fs-extra');

const PROJECT_TYPES = {
  'react-app': { label: 'React App', deps: ['react', 'react-dom', 'react-router-dom'], devDeps: ['vite', '@vitejs/plugin-react', 'tailwindcss', 'autoprefixer', 'postcss'] },
  'nextjs-app': { label: 'Next.js App', deps: ['next', 'react', 'react-dom'], devDeps: ['tailwindcss', 'autoprefixer', 'postcss'] },
  'express-api': { label: 'Express API', deps: ['express', 'cors', 'dotenv', 'morgan'], devDeps: ['nodemon'] },
  'portfolio': { label: 'Portfolio Website', deps: ['react', 'react-dom', 'framer-motion'], devDeps: ['vite', '@vitejs/plugin-react', 'tailwindcss', 'autoprefixer', 'postcss'] },
  'admin-dashboard': { label: 'Admin Dashboard', deps: ['react', 'react-dom', 'recharts', 'react-router-dom'], devDeps: ['vite', '@vitejs/plugin-react', 'tailwindcss', 'autoprefixer', 'postcss'] },
  'landing-page': { label: 'Landing Page', deps: [], devDeps: [] },
  'blog': { label: 'Blog Template', deps: ['react', 'react-dom', 'react-router-dom', 'react-markdown'], devDeps: ['vite', '@vitejs/plugin-react', 'tailwindcss', 'autoprefixer', 'postcss'] },
  'docs-site': { label: 'Documentation Site', deps: ['react', 'react-dom', 'react-router-dom', 'react-markdown', 'prismjs'], devDeps: ['vite', '@vitejs/plugin-react', 'tailwindcss', 'autoprefixer', 'postcss'] },
  'tailwind-website': { label: 'Tailwind Website', deps: [], devDeps: ['tailwindcss', 'autoprefixer', 'postcss'] },
  'resume-builder': { label: 'Resume Builder', deps: ['react', 'react-dom', 'html2canvas', 'jspdf'], devDeps: ['vite', '@vitejs/plugin-react', 'tailwindcss', 'autoprefixer', 'postcss'] },
};

async function generateProject(type, config, projectsDir, templatesDir) {
  const projectName = config.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
  const projectPath = path.join(projectsDir, projectName);

  await fs.ensureDir(projectPath);

  const typeConfig = PROJECT_TYPES[type] || PROJECT_TYPES['react-app'];
  const context = { ...config, projectName, type, typeLabel: typeConfig.label, year: new Date().getFullYear() };

  // Generate files based on type
  const files = getProjectFiles(type, context);

  for (const [filePath, content] of Object.entries(files)) {
    const fullPath = path.join(projectPath, filePath);
    await fs.outputFile(fullPath, replacePlaceholders(content, context));
  }

  // Write project metadata
  await fs.outputJSON(path.join(projectPath, 'project.json'), {
    name: projectName,
    displayName: config.name,
    type,
    description: config.description || '',
    author: config.author || 'Anonymous',
    created: new Date().toISOString(),
    version: '1.0.0',
  }, { spaces: 2 });

  return {
    projectName,
    projectPath,
    fileCount: Object.keys(files).length,
    type,
    installCmd: `cd ${projectName} && npm install`,
    devCmd: type === 'express-api' ? 'npm run dev' : 'npm run dev',
  };
}

function replacePlaceholders(content, ctx) {
  return content
    .replace(/\{\{PROJECT_NAME\}\}/g, ctx.projectName)
    .replace(/\{\{DISPLAY_NAME\}\}/g, ctx.displayName || ctx.name || ctx.projectName)
    .replace(/\{\{DESCRIPTION\}\}/g, ctx.description || 'A project generated by MD Dev Studio')
    .replace(/\{\{AUTHOR\}\}/g, ctx.author || 'Developer')
    .replace(/\{\{YEAR\}\}/g, ctx.year)
    .replace(/\{\{ACCENT_COLOR\}\}/g, ctx.accentColor || '#ff79ee')
    .replace(/\{\{FONT\}\}/g, ctx.font || 'Inter')
    .replace(/\{\{PORT\}\}/g, ctx.port || '3000');
}

function getProjectFiles(type, ctx) {
  const common = getCommonFiles(ctx);
  switch (type) {
    case 'react-app': return { ...common, ...getReactAppFiles(ctx) };
    case 'nextjs-app': return { ...common, ...getNextjsFiles(ctx) };
    case 'express-api': return { ...getExpressFiles(ctx) };
    case 'portfolio': return { ...common, ...getPortfolioFiles(ctx) };
    case 'admin-dashboard': return { ...common, ...getAdminDashboardFiles(ctx) };
    case 'landing-page': return { ...getLandingPageFiles(ctx) };
    case 'blog': return { ...common, ...getBlogFiles(ctx) };
    case 'docs-site': return { ...common, ...getDocsFiles(ctx) };
    case 'tailwind-website': return { ...getTailwindWebsiteFiles(ctx) };
    case 'resume-builder': return { ...common, ...getResumeBuildFiles(ctx) };
    default: return { ...common, ...getReactAppFiles(ctx) };
  }
}

function getCommonFiles(ctx) {
  return {
    '.gitignore': `node_modules\ndist\nbuild\n.env\n.env.local\n*.log\n.DS_Store`,
    'README.md': `# {{DISPLAY_NAME}}\n\n{{DESCRIPTION}}\n\nGenerated by **MD Dev Studio** — offline, AI-free developer platform.\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Author\n\n{{AUTHOR}} · {{YEAR}}\n`,
    '.env': `# Environment variables for {{PROJECT_NAME}}\nVITE_APP_NAME={{DISPLAY_NAME}}\nVITE_ACCENT_COLOR={{ACCENT_COLOR}}\n`,
  };
}

function getReactAppFiles(ctx) {
  return {
    'package.json': JSON.stringify({
      name: '{{PROJECT_NAME}}',
      version: '1.0.0',
      private: true,
      scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
      dependencies: { react: '^18.2.0', 'react-dom': '^18.2.0', 'react-router-dom': '^6.21.0' },
      devDependencies: { '@vitejs/plugin-react': '^4.2.1', vite: '^5.0.0', tailwindcss: '^3.4.0', autoprefixer: '^10.4.16', postcss: '^8.4.32' },
    }, null, 2),
    'vite.config.js': `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nexport default defineConfig({ plugins: [react()] });`,
    'tailwind.config.js': `/** @type {import('tailwindcss').Config} */\nexport default {\n  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],\n  theme: { extend: { colors: { accent: '{{ACCENT_COLOR}}' } } },\n  plugins: [],\n};`,
    'postcss.config.js': `export default { plugins: { tailwindcss: {}, autoprefixer: {} } };`,
    'index.html': `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>{{DISPLAY_NAME}}</title>\n</head>\n<body>\n  <div id="root"></div>\n  <script type="module" src="/src/main.jsx"></script>\n</body>\n</html>`,
    'src/main.jsx': `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport { BrowserRouter } from 'react-router-dom';\nimport App from './App';\nimport './index.css';\n\nReactDOM.createRoot(document.getElementById('root')).render(\n  <React.StrictMode>\n    <BrowserRouter>\n      <App />\n    </BrowserRouter>\n  </React.StrictMode>\n);`,
    'src/index.css': `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n:root {\n  --accent: {{ACCENT_COLOR}};\n}\n\nbody {\n  font-family: '{{FONT}}', sans-serif;\n  background: #0f0f0f;\n  color: #f1f1f1;\n}\n`,
    'src/App.jsx': `import React from 'react';\nimport { Routes, Route } from 'react-router-dom';\nimport Home from './pages/Home';\nimport About from './pages/About';\nimport Navbar from './components/Navbar';\n\nexport default function App() {\n  return (\n    <div className="min-h-screen bg-gray-950">\n      <Navbar />\n      <Routes>\n        <Route path="/" element={<Home />} />\n        <Route path="/about" element={<About />} />\n      </Routes>\n    </div>\n  );\n}`,
    'src/pages/Home.jsx': `import React from 'react';\n\nexport default function Home() {\n  return (\n    <main className="container mx-auto px-4 py-20 text-center">\n      <h1 className="text-5xl font-bold mb-6 bg-gradient-to-r from-pink-400 to-purple-400 bg-clip-text text-transparent">\n        Welcome to {{DISPLAY_NAME}}\n      </h1>\n      <p className="text-xl text-gray-400 max-w-2xl mx-auto">\n        {{DESCRIPTION}}\n      </p>\n    </main>\n  );\n}`,
    'src/pages/About.jsx': `import React from 'react';\n\nexport default function About() {\n  return (\n    <main className="container mx-auto px-4 py-20">\n      <h1 className="text-4xl font-bold mb-4">About</h1>\n      <p className="text-gray-400">Built by {{AUTHOR}} · {{YEAR}}</p>\n    </main>\n  );\n}`,
    'src/components/Navbar.jsx': `import React, { useState } from 'react';\nimport { Link } from 'react-router-dom';\n\nexport default function Navbar() {\n  const [open, setOpen] = useState(false);\n  return (\n    <nav className="bg-gray-900/80 backdrop-blur border-b border-gray-800 sticky top-0 z-50">\n      <div className="container mx-auto px-4 py-3 flex items-center justify-between">\n        <Link to="/" className="text-xl font-bold text-pink-400">{{DISPLAY_NAME}}</Link>\n        <div className="flex gap-6 text-sm text-gray-300">\n          <Link to="/" className="hover:text-white transition">Home</Link>\n          <Link to="/about" className="hover:text-white transition">About</Link>\n        </div>\n      </div>\n    </nav>\n  );\n}`,
    'src/components/Footer.jsx': `import React from 'react';\n\nexport default function Footer() {\n  return (\n    <footer className="border-t border-gray-800 text-center text-gray-500 text-sm py-6">\n      © {{YEAR}} {{AUTHOR}} · Generated by MD Dev Studio\n    </footer>\n  );\n}`,
    'src/hooks/useLocalStorage.js': `import { useState } from 'react';\n\nexport function useLocalStorage(key, initialValue) {\n  const [storedValue, setStoredValue] = useState(() => {\n    try { const item = window.localStorage.getItem(key); return item ? JSON.parse(item) : initialValue; }\n    catch { return initialValue; }\n  });\n  const setValue = (value) => {\n    try { setStoredValue(value); window.localStorage.setItem(key, JSON.stringify(value)); }\n    catch { console.error('localStorage error'); }\n  };\n  return [storedValue, setValue];\n}`,
  };
}

function getExpressFiles(ctx) {
  return {
    'package.json': JSON.stringify({
      name: '{{PROJECT_NAME}}',
      version: '1.0.0',
      scripts: { start: 'node src/index.js', dev: 'nodemon src/index.js' },
      dependencies: { express: '^4.18.2', cors: '^2.8.5', dotenv: '^16.3.1', morgan: '^1.10.0' },
      devDependencies: { nodemon: '^3.0.2' },
    }, null, 2),
    '.gitignore': `node_modules\n.env\n*.log`,
    '.env': `PORT={{PORT}}\nNODE_ENV=development\n`,
    'README.md': `# {{DISPLAY_NAME}} API\n\n{{DESCRIPTION}}\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Endpoints\n\n- GET /api/health\n- GET /api/items\n- GET /api/items/:id\n- POST /api/items\n- PUT /api/items/:id\n- DELETE /api/items/:id\n`,
    'src/index.js': `require('dotenv').config();\nconst express = require('express');\nconst cors = require('cors');\nconst morgan = require('morgan');\nconst routes = require('./routes');\n\nconst app = express();\nconst PORT = process.env.PORT || {{PORT}};\n\napp.use(cors());\napp.use(morgan('dev'));\napp.use(express.json());\napp.use('/api', routes);\n\napp.get('/', (req, res) => res.json({ name: '{{DISPLAY_NAME}}', version: '1.0.0' }));\n\napp.listen(PORT, () => console.log(\`🚀 {{DISPLAY_NAME}} running on port \${PORT}\`));\n`,
    'src/routes/index.js': `const { Router } = require('express');\nconst itemRoutes = require('./items');\n\nconst router = Router();\nrouter.get('/health', (req, res) => res.json({ status: 'ok' }));\nrouter.use('/items', itemRoutes);\n\nmodule.exports = router;\n`,
    'src/routes/items.js': `const { Router } = require('express');\nconst controller = require('../controllers/itemsController');\n\nconst router = Router();\nrouter.get('/', controller.getAll);\nrouter.get('/:id', controller.getOne);\nrouter.post('/', controller.create);\nrouter.put('/:id', controller.update);\nrouter.delete('/:id', controller.remove);\n\nmodule.exports = router;\n`,
    'src/controllers/itemsController.js': `let items = [{ id: 1, name: 'Sample Item', description: 'First item', createdAt: new Date().toISOString() }];\nlet nextId = 2;\n\nexports.getAll = (req, res) => res.json({ success: true, data: items, total: items.length });\nexports.getOne = (req, res) => { const item = items.find(i => i.id === +req.params.id); if (!item) return res.status(404).json({ error: 'Not found' }); res.json({ success: true, data: item }); };\nexports.create = (req, res) => { const item = { id: nextId++, ...req.body, createdAt: new Date().toISOString() }; items.push(item); res.status(201).json({ success: true, data: item }); };\nexports.update = (req, res) => { const idx = items.findIndex(i => i.id === +req.params.id); if (idx === -1) return res.status(404).json({ error: 'Not found' }); items[idx] = { ...items[idx], ...req.body, updatedAt: new Date().toISOString() }; res.json({ success: true, data: items[idx] }); };\nexports.remove = (req, res) => { const idx = items.findIndex(i => i.id === +req.params.id); if (idx === -1) return res.status(404).json({ error: 'Not found' }); items.splice(idx, 1); res.json({ success: true }); };\n`,
    'src/middleware/errorHandler.js': `module.exports = (err, req, res, next) => {\n  console.error(err.stack);\n  res.status(err.status || 500).json({ success: false, error: err.message || 'Internal Server Error' });\n};\n`,
  };
}

function getPortfolioFiles(ctx) {
  const base = getReactAppFiles(ctx);
  return {
    ...base,
    'src/App.jsx': `import React from 'react';\nimport Hero from './components/Hero';\nimport About from './components/About';\nimport Projects from './components/Projects';\nimport Skills from './components/Skills';\nimport Contact from './components/Contact';\nimport Navbar from './components/Navbar';\n\nexport default function App() {\n  return (\n    <div className="min-h-screen bg-gray-950 text-white">\n      <Navbar />\n      <Hero />\n      <About />\n      <Projects />\n      <Skills />\n      <Contact />\n    </div>\n  );\n}`,
    'src/components/Hero.jsx': `import React from 'react';\n\nexport default function Hero() {\n  return (\n    <section className="min-h-screen flex items-center justify-center text-center px-4">\n      <div>\n        <div className="w-32 h-32 rounded-full bg-gradient-to-br from-pink-400 to-purple-600 mx-auto mb-8 flex items-center justify-center text-5xl font-bold">\n          {('{{AUTHOR}}').charAt(0).toUpperCase()}\n        </div>\n        <h1 className="text-6xl font-black mb-4">{{AUTHOR}}</h1>\n        <p className="text-2xl text-pink-400 mb-6">Full Stack Developer</p>\n        <p className="text-gray-400 max-w-xl mx-auto mb-8">{{DESCRIPTION}}</p>\n        <div className="flex gap-4 justify-center">\n          <a href="#projects" className="bg-pink-500 hover:bg-pink-400 text-white px-8 py-3 rounded-full font-semibold transition">View Work</a>\n          <a href="#contact" className="border border-gray-600 hover:border-pink-400 text-white px-8 py-3 rounded-full font-semibold transition">Contact Me</a>\n        </div>\n      </div>\n    </section>\n  );\n}`,
    'src/components/Projects.jsx': `import React from 'react';\n\nconst projects = [\n  { title: 'Project Alpha', desc: 'A full-stack web application', tech: ['React', 'Node.js', 'MongoDB'], link: '#' },\n  { title: 'Project Beta', desc: 'Mobile-first dashboard', tech: ['React Native', 'Firebase'], link: '#' },\n  { title: 'Project Gamma', desc: 'REST API service', tech: ['Express', 'PostgreSQL'], link: '#' },\n];\n\nexport default function Projects() {\n  return (\n    <section id="projects" className="py-20 px-4 max-w-6xl mx-auto">\n      <h2 className="text-4xl font-black text-center mb-12">Projects</h2>\n      <div className="grid md:grid-cols-3 gap-6">\n        {projects.map((p, i) => (\n          <div key={i} className="bg-gray-900 rounded-2xl p-6 border border-gray-800 hover:border-pink-500 transition">\n            <h3 className="text-xl font-bold mb-2">{p.title}</h3>\n            <p className="text-gray-400 mb-4">{p.desc}</p>\n            <div className="flex flex-wrap gap-2">\n              {p.tech.map(t => <span key={t} className="text-xs bg-pink-500/20 text-pink-300 px-2 py-1 rounded">{t}</span>)}\n            </div>\n          </div>\n        ))}\n      </div>\n    </section>\n  );\n}`,
    'src/components/Skills.jsx': `import React from 'react';\n\nconst skills = ['JavaScript', 'TypeScript', 'React', 'Node.js', 'Python', 'SQL', 'Git', 'Docker', 'AWS', 'Figma'];\n\nexport default function Skills() {\n  return (\n    <section id="skills" className="py-20 px-4 bg-gray-900">\n      <div className="max-w-4xl mx-auto text-center">\n        <h2 className="text-4xl font-black mb-12">Skills</h2>\n        <div className="flex flex-wrap justify-center gap-3">\n          {skills.map(s => (\n            <span key={s} className="bg-gray-800 border border-gray-700 text-white px-4 py-2 rounded-full text-sm hover:border-pink-400 transition">{s}</span>\n          ))}\n        </div>\n      </div>\n    </section>\n  );\n}`,
    'src/components/About.jsx': `import React from 'react';\n\nexport default function About() {\n  return (\n    <section id="about" className="py-20 px-4 bg-gray-900">\n      <div className="max-w-3xl mx-auto text-center">\n        <h2 className="text-4xl font-black mb-6">About Me</h2>\n        <p className="text-gray-400 text-lg leading-relaxed">{{DESCRIPTION}} Passionate about building clean, scalable software solutions. Always learning, always shipping.</p>\n      </div>\n    </section>\n  );\n}`,
    'src/components/Contact.jsx': `import React, { useState } from 'react';\n\nexport default function Contact() {\n  const [sent, setSent] = useState(false);\n  return (\n    <section id="contact" className="py-20 px-4">\n      <div className="max-w-xl mx-auto text-center">\n        <h2 className="text-4xl font-black mb-8">Get In Touch</h2>\n        {sent ? <p className="text-green-400 text-lg">Message saved locally!</p> : (\n          <form onSubmit={e => { e.preventDefault(); setSent(true); }} className="space-y-4">\n            <input required placeholder="Your Name" className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-3 text-white focus:border-pink-400 outline-none" />\n            <input required type="email" placeholder="Email" className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-3 text-white focus:border-pink-400 outline-none" />\n            <textarea required rows={4} placeholder="Message" className="w-full bg-gray-900 border border-gray-700 rounded-xl px-4 py-3 text-white focus:border-pink-400 outline-none resize-none" />\n            <button className="w-full bg-pink-500 hover:bg-pink-400 text-white py-3 rounded-xl font-semibold transition">Send Message</button>\n          </form>\n        )}\n      </div>\n    </section>\n  );\n}`,
  };
}

function getAdminDashboardFiles(ctx) {
  const base = getReactAppFiles(ctx);
  return {
    ...base,
    'src/App.jsx': `import React, { useState } from 'react';\nimport Sidebar from './components/Sidebar';\nimport Dashboard from './pages/Dashboard';\nimport Analytics from './pages/Analytics';\nimport Users from './pages/Users';\nimport Settings from './pages/Settings';\n\nexport default function App() {\n  const [page, setPage] = useState('dashboard');\n  const pages = { dashboard: <Dashboard />, analytics: <Analytics />, users: <Users />, settings: <Settings /> };\n  return (\n    <div className="flex min-h-screen bg-gray-950">\n      <Sidebar current={page} onNavigate={setPage} />\n      <main className="flex-1 p-8 overflow-auto">{pages[page]}</main>\n    </div>\n  );\n}`,
    'src/components/Sidebar.jsx': `import React from 'react';\n\nconst navItems = [\n  { id: 'dashboard', label: 'Dashboard', icon: '⊞' },\n  { id: 'analytics', label: 'Analytics', icon: '📊' },\n  { id: 'users', label: 'Users', icon: '👥' },\n  { id: 'settings', label: 'Settings', icon: '⚙️' },\n];\n\nexport default function Sidebar({ current, onNavigate }) {\n  return (\n    <aside className="w-60 bg-gray-900 border-r border-gray-800 flex flex-col">\n      <div className="p-6 border-b border-gray-800">\n        <h1 className="text-xl font-black text-pink-400">{{DISPLAY_NAME}}</h1>\n        <p className="text-xs text-gray-500 mt-1">Admin Panel</p>\n      </div>\n      <nav className="flex-1 p-4 space-y-1">\n        {navItems.map(item => (\n          <button key={item.id} onClick={() => onNavigate(item.id)}\n            className={\`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm transition \${current === item.id ? 'bg-pink-500/20 text-pink-400' : 'text-gray-400 hover:bg-gray-800'}\`}>\n            <span>{item.icon}</span>{item.label}\n          </button>\n        ))}\n      </nav>\n      <div className="p-4 border-t border-gray-800 text-xs text-gray-600 text-center">{{AUTHOR}} · {{YEAR}}</div>\n    </aside>\n  );\n}`,
    'src/pages/Dashboard.jsx': `import React from 'react';\n\nconst stats = [{ label: 'Total Users', value: '12,483', change: '+8.2%', up: true },{ label: 'Revenue', value: '$94,201', change: '+12.5%', up: true },{ label: 'Orders', value: '3,842', change: '-2.1%', up: false },{ label: 'Active Now', value: '284', change: '+19.0%', up: true }];\n\nexport default function Dashboard() {\n  return (\n    <div>\n      <h1 className="text-3xl font-black mb-8">Dashboard</h1>\n      <div className="grid grid-cols-4 gap-4 mb-8">\n        {stats.map((s, i) => (\n          <div key={i} className="bg-gray-900 rounded-2xl p-6 border border-gray-800">\n            <p className="text-gray-400 text-sm mb-2">{s.label}</p>\n            <p className="text-3xl font-black mb-1">{s.value}</p>\n            <p className={\`text-sm font-medium \${s.up ? 'text-green-400' : 'text-red-400'}\`}>{s.change}</p>\n          </div>\n        ))}\n      </div>\n    </div>\n  );\n}`,
    'src/pages/Analytics.jsx': `import React from 'react';\nexport default function Analytics() { return <div><h1 className="text-3xl font-black mb-6">Analytics</h1><p className="text-gray-400">Charts and data visualization would go here.</p></div>; }`,
    'src/pages/Users.jsx': `import React from 'react';\nconst users = [{ name: 'Alice Johnson', email: 'alice@example.com', role: 'Admin', status: 'Active' },{ name: 'Bob Smith', email: 'bob@example.com', role: 'Editor', status: 'Active' },{ name: 'Carol White', email: 'carol@example.com', role: 'Viewer', status: 'Inactive' }];\nexport default function Users() {\n  return (\n    <div>\n      <h1 className="text-3xl font-black mb-6">Users</h1>\n      <div className="bg-gray-900 rounded-2xl border border-gray-800 overflow-hidden">\n        <table className="w-full">\n          <thead className="border-b border-gray-800"><tr className="text-left text-gray-400 text-sm"><th className="px-6 py-4">Name</th><th className="px-6 py-4">Email</th><th className="px-6 py-4">Role</th><th className="px-6 py-4">Status</th></tr></thead>\n          <tbody>{users.map((u, i) => <tr key={i} className="border-b border-gray-800 last:border-0"><td className="px-6 py-4 font-medium">{u.name}</td><td className="px-6 py-4 text-gray-400">{u.email}</td><td className="px-6 py-4"><span className="text-xs bg-pink-500/20 text-pink-300 px-2 py-1 rounded">{u.role}</span></td><td className="px-6 py-4"><span className={\`text-xs px-2 py-1 rounded \${u.status === 'Active' ? 'bg-green-500/20 text-green-400' : 'bg-gray-700 text-gray-400'}\`}>{u.status}</span></td></tr>)}</tbody>\n        </table>\n      </div>\n    </div>\n  );\n}`,
    'src/pages/Settings.jsx': `import React from 'react';\nexport default function Settings() { return <div><h1 className="text-3xl font-black mb-6">Settings</h1><p className="text-gray-400">Configuration and preferences.</p></div>; }`,
  };
}

function getLandingPageFiles(ctx) {
  return {
    'index.html': `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>{{DISPLAY_NAME}}</title>\n  <link rel="preconnect" href="https://fonts.googleapis.com" />\n  <link href="https://fonts.googleapis.com/css2?family={{FONT}}:wght@400;600;700;900&display=swap" rel="stylesheet" />\n  <style>\n    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n    body { font-family: '{{FONT}}', sans-serif; background: #080808; color: #f1f1f1; line-height: 1.6; }\n    .container { max-width: 1100px; margin: 0 auto; padding: 0 2rem; }\n    nav { padding: 1.5rem 0; display: flex; justify-content: space-between; align-items: center; }\n    .logo { font-weight: 900; font-size: 1.4rem; color: {{ACCENT_COLOR}}; }\n    .nav-links a { color: #aaa; text-decoration: none; margin-left: 2rem; transition: color 0.2s; }\n    .nav-links a:hover { color: #fff; }\n    .hero { min-height: 90vh; display: flex; align-items: center; text-align: center; }\n    .hero-content { max-width: 800px; margin: 0 auto; }\n    h1 { font-size: clamp(2.5rem, 8vw, 6rem); font-weight: 900; line-height: 1.05; margin-bottom: 1.5rem; }\n    .gradient-text { background: linear-gradient(135deg, {{ACCENT_COLOR}}, #a78bfa); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }\n    .subtitle { font-size: 1.25rem; color: #888; max-width: 600px; margin: 0 auto 2.5rem; }\n    .btn { display: inline-block; padding: 1rem 2.5rem; border-radius: 9999px; font-weight: 700; text-decoration: none; transition: all 0.2s; }\n    .btn-primary { background: {{ACCENT_COLOR}}; color: #000; }\n    .btn-primary:hover { opacity: 0.9; transform: translateY(-2px); }\n    .btn-secondary { border: 1px solid #333; color: #fff; margin-left: 1rem; }\n    .btn-secondary:hover { border-color: {{ACCENT_COLOR}}; }\n    .features { padding: 6rem 0; }\n    .features h2 { font-size: 3rem; font-weight: 900; text-align: center; margin-bottom: 4rem; }\n    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 2rem; }\n    .card { background: #111; border: 1px solid #222; border-radius: 1.5rem; padding: 2rem; transition: border-color 0.2s; }\n    .card:hover { border-color: {{ACCENT_COLOR}}40; }\n    .card-icon { font-size: 2rem; margin-bottom: 1rem; }\n    .card h3 { font-weight: 700; font-size: 1.2rem; margin-bottom: 0.5rem; }\n    .card p { color: #888; font-size: 0.95rem; }\n    footer { border-top: 1px solid #1a1a1a; padding: 2rem 0; text-align: center; color: #444; font-size: 0.875rem; }\n  </style>\n</head>\n<body>\n  <div class="container">\n    <nav>\n      <span class="logo">{{DISPLAY_NAME}}</span>\n      <div class="nav-links">\n        <a href="#features">Features</a>\n        <a href="#about">About</a>\n        <a href="#contact">Contact</a>\n      </div>\n    </nav>\n    <section class="hero">\n      <div class="hero-content">\n        <h1>The Future<br /><span class="gradient-text">Starts Here</span></h1>\n        <p class="subtitle">{{DESCRIPTION}}</p>\n        <a href="#features" class="btn btn-primary">Get Started</a>\n        <a href="#about" class="btn btn-secondary">Learn More</a>\n      </div>\n    </section>\n    <section class="features" id="features">\n      <h2>Features</h2>\n      <div class="grid">\n        <div class="card"><div class="card-icon">⚡</div><h3>Lightning Fast</h3><p>Optimized for performance from the ground up.</p></div>\n        <div class="card"><div class="card-icon">🔒</div><h3>Secure by Default</h3><p>Built with security best practices in mind.</p></div>\n        <div class="card"><div class="card-icon">🎨</div><h3>Beautiful Design</h3><p>Pixel-perfect UI that delights users.</p></div>\n        <div class="card"><div class="card-icon">📱</div><h3>Responsive</h3><p>Works beautifully on all devices.</p></div>\n        <div class="card"><div class="card-icon">🛠️</div><h3>Customizable</h3><p>Easily adapt to your specific needs.</p></div>\n        <div class="card"><div class="card-icon">🚀</div><h3>Easy Deploy</h3><p>One command to take it live.</p></div>\n      </div>\n    </section>\n    <footer>© {{YEAR}} {{AUTHOR}} · Generated by MD Dev Studio</footer>\n  </div>\n</body>\n</html>`,
    '.gitignore': '.DS_Store\n*.log',
    'README.md': `# {{DISPLAY_NAME}}\n\n{{DESCRIPTION}}\n\nGenerated by **MD Dev Studio**.\n\n## Usage\n\nOpen \`index.html\` in your browser, or serve with:\n\n\`\`\`bash\nnpx serve .\n\`\`\`\n`,
  };
}

function getBlogFiles(ctx) {
  const base = getReactAppFiles(ctx);
  return {
    ...base,
    'src/App.jsx': `import React from 'react';\nimport { Routes, Route } from 'react-router-dom';\nimport Navbar from './components/Navbar';\nimport Home from './pages/Home';\nimport Post from './pages/Post';\n\nexport default function App() {\n  return (\n    <div className="min-h-screen bg-gray-950 text-white">\n      <Navbar />\n      <Routes>\n        <Route path="/" element={<Home />} />\n        <Route path="/post/:id" element={<Post />} />\n      </Routes>\n    </div>\n  );\n}`,
    'src/data/posts.js': `export const posts = [\n  { id: 1, title: 'Getting Started with React', excerpt: 'Learn the basics of React in this comprehensive guide.', date: '2024-01-15', readTime: '5 min', tags: ['React', 'JavaScript'], content: '# Getting Started with React\\n\\nReact is a powerful library for building user interfaces...' },\n  { id: 2, title: 'Mastering Tailwind CSS', excerpt: 'Tips and tricks for building beautiful UIs with Tailwind.', date: '2024-01-20', readTime: '8 min', tags: ['CSS', 'Tailwind'], content: '# Mastering Tailwind CSS\\n\\nTailwind CSS revolutionizes how we write styles...' },\n  { id: 3, title: 'Node.js Best Practices', excerpt: 'Write cleaner, more maintainable Node.js applications.', date: '2024-01-25', readTime: '10 min', tags: ['Node.js', 'Backend'], content: '# Node.js Best Practices\\n\\nBuilding scalable backend applications...' },\n];\n`,
    'src/pages/Home.jsx': `import React from 'react';\nimport { Link } from 'react-router-dom';\nimport { posts } from '../data/posts';\n\nexport default function Home() {\n  return (\n    <main className="container mx-auto px-4 py-12 max-w-4xl">\n      <h1 className="text-5xl font-black mb-3">{{DISPLAY_NAME}}</h1>\n      <p className="text-gray-400 mb-12">{{DESCRIPTION}}</p>\n      <div className="space-y-8">\n        {posts.map(post => (\n          <article key={post.id} className="border-b border-gray-800 pb-8">\n            <div className="flex items-center gap-3 text-xs text-gray-500 mb-3">\n              <time>{post.date}</time>\n              <span>·</span>\n              <span>{post.readTime} read</span>\n              {post.tags.map(t => <span key={t} className="bg-pink-500/20 text-pink-300 px-2 py-0.5 rounded">{t}</span>)}\n            </div>\n            <h2 className="text-2xl font-bold mb-2 hover:text-pink-400 transition"><Link to={'/post/'+post.id}>{post.title}</Link></h2>\n            <p className="text-gray-400 mb-4">{post.excerpt}</p>\n            <Link to={'/post/'+post.id} className="text-pink-400 text-sm font-semibold hover:underline">Read more →</Link>\n          </article>\n        ))}\n      </div>\n    </main>\n  );\n}`,
    'src/pages/Post.jsx': `import React from 'react';\nimport { useParams, Link } from 'react-router-dom';\nimport { posts } from '../data/posts';\n\nexport default function Post() {\n  const { id } = useParams();\n  const post = posts.find(p => p.id === +id);\n  if (!post) return <div className="container mx-auto px-4 py-12"><p>Post not found.</p><Link to="/" className="text-pink-400">← Back</Link></div>;\n  return (\n    <main className="container mx-auto px-4 py-12 max-w-3xl">\n      <Link to="/" className="text-pink-400 text-sm hover:underline">← Back to blog</Link>\n      <h1 className="text-4xl font-black mt-6 mb-3">{post.title}</h1>\n      <div className="text-gray-500 text-sm mb-8">{post.date} · {post.readTime} read</div>\n      <div className="prose prose-invert max-w-none">\n        {post.content.split('\\n').map((line, i) => line.startsWith('# ') ? <h1 key={i} className="text-3xl font-black mt-8 mb-4">{line.slice(2)}</h1> : <p key={i} className="text-gray-300 mb-4">{line}</p>)}\n      </div>\n    </main>\n  );\n}`,
  };
}

function getDocsFiles(ctx) {
  return { ...getReactAppFiles(ctx) };
}
function getTailwindWebsiteFiles(ctx) {
  return { ...getLandingPageFiles(ctx) };
}
function getResumeBuildFiles(ctx) {
  return { ...getReactAppFiles(ctx) };
}
function getNextjsFiles(ctx) {
  return {
    'package.json': JSON.stringify({ name: '{{PROJECT_NAME}}', version: '1.0.0', scripts: { dev: 'next dev', build: 'next build', start: 'next start' }, dependencies: { next: '^14.0.0', react: '^18.2.0', 'react-dom': '^18.2.0' }, devDependencies: { tailwindcss: '^3.4.0', autoprefixer: '^10.4.16', postcss: '^8.4.32' } }, null, 2),
    'app/page.jsx': `export default function Home() { return <main><h1>{{DISPLAY_NAME}}</h1><p>{{DESCRIPTION}}</p></main>; }`,
    'app/layout.jsx': `export const metadata = { title: '{{DISPLAY_NAME}}', description: '{{DESCRIPTION}}' };\nexport default function RootLayout({ children }) { return <html lang="en"><body>{children}</body></html>; }`,
    'next.config.js': `/** @type {import('next').NextConfig} */\nmodule.exports = {};`,
    'tailwind.config.js': `module.exports = { content: ['./app/**/*.{js,jsx,ts,tsx}'], theme: { extend: {} }, plugins: [] };`,
    'postcss.config.js': `module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } };`,
    'app/globals.css': `@tailwind base;\n@tailwind components;\n@tailwind utilities;`,
    '.gitignore': `node_modules\n.next\n.env.local`,
    'README.md': `# {{DISPLAY_NAME}}\n\n{{DESCRIPTION}}\n\n\`\`\`bash\nnpm install && npm run dev\n\`\`\`\n`,
  };
}

module.exports = { generateProject, PROJECT_TYPES };
